" 構文チェック
syntax enable

" カラースキーム変更
colorscheme desert

" エンコーディング
set encoding=UTF-8
set fileencoding=UTF-8
set termencoding=UTF-8

" クリップボード有効化
set clipboard+=unnamed

" 行番号を表示
"set number
set relativenumber

" netrw: 行番号を表示
let g:netrw_bufsettings = 'noma nomod relativenumber nobl nowrap ro'
" netrw: 非表示ファイルを設定
let g:netrw_list_hide = '^\./$,\(^\|\s\s\)\zs\.\S\+'
" netrw: 初期表示は非表示ファイルなし
let g:netrw_hide=1

" 対応括弧をハイライト表示する
set showmatch

" タブ文字幅
set tabstop=2
" 自動インデントの幅
set shiftwidth=2

" Ctr+[でインサートされる問題の解決
imap <Nul> <Nop>
" Backspaceが効かない問題の解決
set backspace=indent,eol,start

