" 構文チェック
syntax enable

" カラースキーム変更
colorscheme desert

" エンコーディング
set encoding=UTF-8
set fileencoding=UTF-8
set termencoding=UTF-8

" クリップボード有効化
set clipboard+=unnamed

" 行番号を表示
set number
set relativenumber

" 対応括弧をハイライト表示する
set showmatch

" タブ文字幅
set tabstop=2
" 自動インデントの幅
set shiftwidth=2

" コロンセミコロン入れ変え
noremap ; :
noremap : ;

" Turn off paste mode when leaving insert
autocmd InsertLeave * set nopaste

" Ctr+[でインサートされる問題の解決
imap <Nul> <Nop>
" Backspaceが効かない問題の解決
set backspace=indent,eol,start

" ショートカット
" 次のウィンドウに移動
map @w <C-w>w

