
" neobundle
" Note: Skip initialization for vim-tiny or vim-small.
if 0 | endif

if &compatible
 set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=~/.vim/bundle/neobundle.vim/

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'plasticboy/vim-markdown'
NeoBundle 'kannokanno/previm'
NeoBundle 'tyru/open-browser.vim'

" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!

call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
au BufRead,BufNewFile *.md set filetype=markdown

" plasticboy/vim-markdown
" 折りたたみの禁止
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_auto_insert_bullets = 0
let g:vim_markdown_new_list_item_indent = 0

" kannokanno/previm
autocmd BufRead,BufNewFile *.md set filetype=markdown
let g:previm_open_cmd = 'open -a Google\ Chrome'
" ctrl pでプレビュー
nnoremap <silent> <C-p> :PrevimOpen<CR>

" tyru/open-browser.vim
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)

" 構文チェック
syntax enable

" カラースキーム変更
colorscheme desert

" エンコーディング
set encoding=UTF-8
set fileencoding=UTF-8
set termencoding=UTF-8

" クリップボード有効化
set clipboard+=unnamed

" 行番号を表示
set number
set relativenumber

" 対応括弧をハイライト表示する
set showmatch

" タブ文字幅
set tabstop=2
" 自動インデントの幅
set shiftwidth=2

" コロンセミコロン入れ変え
noremap ; :
noremap : ;

" Turn off paste mode when leaving insert
autocmd InsertLeave * set nopaste

" Ctr+[でインサートされる問題の解決
imap <Nul> <Nop>
" Backspaceが効かない問題の解決
set backspace=indent,eol,start

" ショートカット
" 次のウィンドウに移動
map @w <C-w>w

" netrw: 行番号を表示
let g:netrw_bufsettings='noma nomod relativenumber nobl nowrap ro'
" netrw: 非表示ファイルを設定(./だけは表示）
let g:netrw_list_hide='\(\(^\|\s\s\)\zs\.\S\+/\|\(^\|\s\s\)\zs\.\S\+[^/]\)'
" netrw: 初期表示は非表示ファイルなし
let g:netrw_hide=1
" netrw: rmでディレクトリも消す（動かない）
"let g:netrw_localrmdir='/bin/rm -r'
" netrw: カレントディレクトリを追随する
let g:netrw_keepdir=0
" netrw: ファイル・ディレクトリを消す（危険なので停止）
"noremap @D ^<C-V>$y:echo system('rm -rf '.@")<CR><C-l>:echo 'delete '.@"<CR>
" netrw: ファイル・ディレクトリを確認
noremap @l ^<C-V>$y:echo 'rm -rf '.@"<CR>
" netrw: ファイル・ディレクトリを消すコマンドをコピー
noremap @d ^<C-V>$y:echo system('echo -n :!rm -rf ./'.@".'\|pbcopy')<CR>:echo 'copy > rm -rf ./'.@"<CR>
" nettw: もう一つのペインのディレクトリターゲットにする
map @t <C-w>w0gg/^\./<CR>mt<C-w>w

