export GOROOT="/usr/local/opt/go/libexec"
export GOPATH=$HOME/go

export PATH=$GOROOT/bin:$GOPATH/bin:$HOME/bin:$HOME/.nodebrew/current/bin:$HOME/.pyenv/shims:$PATH
export PATH=$GOROOT/bin:$GOPATH/bin:$HOME/bin:$HOME/.nodebrew/current/bin:$PATH
export JAVA_HOME=`/usr/libexec/java_home -v 11`
export AWS_DEFAULT_REGION=ap-northeast-1

