# .zshrc
export PS1="%10F%m%f:%11F%1~%f \$ "

# .zsh.local
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
## プロセスを横断してヒストリを共有
setopt inc_append_history
## ヒストリの共有の有効化
setopt share_history
## 直前と同じコマンドをヒストリに追加しない
setopt hist_ignore_dups
## ヒストリに追加されるコマンドが古いものと同じなら古いものを削除
setopt hist_ignore_all_dups
## 余分な空白は詰めて記録
setopt hist_reduce_blanks

# fzf
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey "ç" fzf-cd-widget

