# .zshrc
export PS1="%10F%m%f:%11F%1~%f \$ "

alias git.dotfiles='cd ~/Documents/GitHub/dotfiles/'
alias git.sample='cd ~/Documents/GitHub/Sample/'
alias git.eikatou.net='cd ~/Documents/GitHub/eikatou.net/'
