alias hi='history 10'
alias d1Ubuntu='docker run -it --rm --entrypoint /bin/bash ubuntu'
alias pcopy='tr -d '\n' | pbcopy'
alias pwdc='pwd | tr -d '\''\n'\'' | pbcopy'
alias pwdcc='pwd | sed "s/^\(.*\)$/'\''\1'\''/" | tr -d '\''\n'\'' | pbcopy'

shopt -s expand_aliases
unset BASH_ENV
